server:
  port: 10000
  ssl:
    enabled: false

springfox:
  documentation:
    swagger:
      v2:
        path: "/v2/api-docs"

logging:
  level:
    root: INFO
  nl:
    elstarit:
      reactive: DEBUG

info:
  app:
    name: Reactive Streams Starter
    version: 1.0.0-SNAPSHOT
    description: Reactive Streams Starter
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: Reactive Streams Starter
    stub: false
  profiles:
    active: local #@activeProfile@

---
spring:
  profiles: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/stream-store

service:
  cors:
    origins: http://localhost:4200 #list of domains seperated by a comma
    allowedMethods: POST, OPTIONS, GET, PATCH, DELETE
swagger:
  enabled: true

topic-management:
  url: http://localhost:10000/reactive/streams/preference

---
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/stream-store
service:
  cors:
    origins: http://localhost:8080, http://localhost:8000, http://localhost:4200 #list of domains seperated by a comma
    allowedMethods: POST, OPTIONS, GET, PATCH, DELETE
swagger:
  enabled: true

topic-management:
  url: http://localhost:10000/reactive/streams/preference
---
spring:
  profiles: prod
  data:
    mongodb:
      uri: mongodb://localhost:27017/stream-store
service:
  cors:
    origins: http://localhost:8080, http://localhost:8000, http://localhost:4200 #list of domains seperated by a comma
    allowedMethods: POST, OPTIONS, GET, PATCH, DELETE

swagger:
  enabled: false

topic-management:
  url: http://localhost:10000/reactive/streams/preference
---