server:
  port: 10000
  ssl:
    enabled: false

logging:
  level:
    root: INFO
  nl:
    rabobank:
      gict:
        crmvirtual:
          relevance:
            sectorknowledge:
              topicmanagementservice: DEBUG

info:
  app:
    name: Topic Management Service
    version: 1.0.0-SNAPSHOT
    description: Topic Management Service
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: Topic Management Service
    stub: false
  profiles:
    active: local #@activeProfile@

---
spring:
  profiles: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/stream-store

service:
  cors:
    origins: http://localhost:8080, http://localhost:8000 #list of domains seperated by a comma
    allowedMethods: POST, OPTIONS, GET, PATCH, DELETE
swagger:
  enabled: true

topic-management:
  url: http://localhost:10000/reactive/streams/preference

---
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/stream-store
service:
  cors:
    origins: http://localhost:8080, http://localhost:8000 #list of domains seperated by a comma
    allowedMethods: POST, OPTIONS, GET, PATCH, DELETE
swagger:
  enabled: true

topic-management:
  url: http://localhost:10000/reactive/streams/preference
---
spring:
  profiles: prod
  data:
    mongodb:
      uri: mongodb://localhost:27017/stream-store
service:
  cors:
    origins: http://localhost:8080, http://localhost:8000 #list of domains seperated by a comma
    allowedMethods: POST, OPTIONS, GET, PATCH, DELETE

swagger:
  enabled: false

topic-management:
  url: http://localhost:10000/reactive/streams/preference
---